export const images = {
    title: require('../assets/images/title.png'), // Update with the correct path
    logo1: require('../assets/images/logo1.png'), // Update with the correct path
    logo2: require('../assets/images/logo2.png'),
    logo3: require('../assets/images/logo3.png'),
    logo4: require('../assets/images/grouplogo.png'),
    logo5: require('../assets/images/logo4.png'),
    google: require('../assets/images/Google.png'),
    apple: require('../assets/images/Apple.png'),
    facebook: require('../assets/images/Facebook.png'),
    logosuccess: require('../assets/images/logosuccess.png'),
    homescreenbg: require('../assets/images/homescreenbg.png'),
    homepagecoins: require('../assets/images/homepagecoins.png'),
    applogo: require('../assets/images/logo.jpeg'),
    beyondlogiclogo:require('../assets/images/beyondlogic.png'),
    homescreenbg1:require('../assets/images/homescreenbg1.png'),
    arcaderobo:require('../assets/images/arcaderobo.png'),
    classicimg:require('../assets/images/classicimg.png'),
    arcadeimg:require('../assets/images/arcadeimg.png'),
    profilepicture:require('../assets/images/pp.png'),
    coin:require('../assets/images/coin.png'),
    badge:require('../assets/images/badge.png'),
    trophy:require('../assets/images/trophy.png'),
    rank:require('../assets/images/rank.png'),
    xp:require('../assets/images/xp.png'),
    avgtime:require('../assets/images/avgtime.png'),
    correct:require('../assets/images/correct.png'),
    IQ:require('../assets/images/IQ.png'),
    coins:require('../assets/images/coins.png'),
    starlayer:require('../assets/images/starlayer.png'),
    profilepic:require('../assets/images/profilepic.png'),
    homescreenbg12:require('../assets/images/homescreenbg12.png'),
    quizpassedimg:require('../assets/images/quizpassedimg.png'),
    challengepassedimg:require('../assets/images/challengepassedimg.png'),
    top3img:require('../assets/images/Top3img.png'),
    crown:require('../assets/images/crown.png'),
    homescreenbg11:require('../assets/images/homescreenbg11.png'),
  };
  